<?xml version="1.0" encoding="utf-8"?><Database Name="EpiloggerV1" Class="TweetsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=Epilogger.com;Initial Catalog=EpiloggerV1;Persist Security Info=True;User ID=sa" SettingsObjectName="DataCollector.My.MySettings" SettingsPropertyName="EpiloggerConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Tweets" Member="Tweets">
    <Type Name="Tweet">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TwitterID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="TextAsHTML" Type="System.String" DbType="NVarChar(1500)" CanBeNull="true" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToUserID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FromUserID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FromUserScreenName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ToUserScreenName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsoLanguageCode" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ProfileImageURL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SinceID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RawSource" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DeleteVoteCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tweet_URL" Member="URLs" ThisKey="ID" OtherKey="TweetID" Type="URL" />
      <Association Name="Event_Tweet" Member="Event" ThisKey="EventID" OtherKey="ID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.URLs" Member="URLs">
    <Type Name="URL">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TweetID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ShortURL" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DeleteVoteCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Tweet_URL" Member="Tweet" ThisKey="TweetID" OtherKey="ID" Type="Tweet" IsForeignKey="true" />
      <Association Name="Event_URL" Member="Event" ThisKey="EventID" OtherKey="ID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Venues" Member="Venues">
    <Type Name="Venue">
      <Column Name="VenueID" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CrossStreet" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Geolat" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Geolong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Venue_Event" Member="Events" ThisKey="VenueID" OtherKey="VenueID" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Images" Member="EpiloggerImages">
    <Type Name="EpiloggerImage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AzureContainerPrefix" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Fullsize" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="Thumb" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="OriginalImageLink" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DeleteVoteCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="EpiloggerImage_EpiloggerImageMetaData" Member="EpiloggerImageMetaDatas" Storage="_ImageMetaDatas" ThisKey="ID" OtherKey="ImageID" Type="EpiloggerImageMetaData" />
      <Association Name="Event_EpiloggerImage" Member="Event" ThisKey="EventID" OtherKey="ID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ImageMetaData" Member="EpiloggerImageMetaDatas">
    <Type Name="EpiloggerImageMetaData">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImageID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ImageSource" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TwitterID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="TwitterName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="EpiloggerImage_EpiloggerImageMetaData" Member="EpiloggerImage" ThisKey="ImageID" OtherKey="ID" Type="EpiloggerImage" IsForeignKey="true" />
      <Association Name="Event_EpiloggerImageMetaData" Member="Event" ThisKey="EventID" OtherKey="ID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CheckIns" Member="CheckIns">
    <Type Name="CheckIn">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TweetID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CheckInDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FourSquareCheckInURL" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Event_CheckIn" Member="Event" ThisKey="EventID" OtherKey="ID" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SubTitle" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WebsiteURL" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Cost" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="StartDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TimeZoneOffset" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VenueID" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="SearchTerms" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NumberOfTweets" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="IsPrivate" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsAdult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CollectionMode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventStatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Event_Tweet" Member="Tweets" ThisKey="ID" OtherKey="EventID" Type="Tweet" />
      <Association Name="Event_URL" Member="URLs" ThisKey="ID" OtherKey="EventID" Type="URL" />
      <Association Name="Event_EpiloggerImage" Member="EpiloggerImages" ThisKey="ID" OtherKey="EventID" Type="EpiloggerImage" />
      <Association Name="Event_EpiloggerImageMetaData" Member="EpiloggerImageMetaDatas" ThisKey="ID" OtherKey="EventID" Type="EpiloggerImageMetaData" />
      <Association Name="Event_CheckIn" Member="CheckIns" ThisKey="ID" OtherKey="EventID" Type="CheckIn" />
      <Association Name="Venue_Event" Member="Venue" ThisKey="VenueID" OtherKey="VenueID" Type="Venue" IsForeignKey="true" />
    </Type>
  </Table>
</Database>