#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoursquareNET.Schema
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	internal partial class SchemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SchemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SchemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Checkin> Checkins
		{
			get
			{
				return this.GetTable<Checkin>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Venue> Venues
		{
			get
			{
				return this.GetTable<Venue>();
			}
		}
		
		public System.Data.Linq.Table<Mayor> Mayors
		{
			get
			{
				return this.GetTable<Mayor>();
			}
		}
		
		public System.Data.Linq.Table<Badge> Badges
		{
			get
			{
				return this.GetTable<Badge>();
			}
		}
		
		public System.Data.Linq.Table<Score> Scores
		{
			get
			{
				return this.GetTable<Score>();
			}
		}
		
		public System.Data.Linq.Table<Special> Specials
		{
			get
			{
				return this.GetTable<Special>();
			}
		}
		
		public System.Data.Linq.Table<Category> Categories
		{
			get
			{
				return this.GetTable<Category>();
			}
		}
		
		public System.Data.Linq.Table<Settings> Settings
		{
			get
			{
				return this.GetTable<Settings>();
			}
		}
		
		internal System.Data.Linq.Table<UserObj> UserObjs
		{
			get
			{
				return this.GetTable<UserObj>();
			}
		}
		
		internal System.Data.Linq.Table<CheckinsObj> CheckinsObjs
		{
			get
			{
				return this.GetTable<CheckinsObj>();
			}
		}
		
		internal System.Data.Linq.Table<BadgeObj> BadgeObjs
		{
			get
			{
				return this.GetTable<BadgeObj>();
			}
		}
		
		internal System.Data.Linq.Table<CheckinObj> CheckinObjs
		{
			get
			{
				return this.GetTable<CheckinObj>();
			}
		}
		
		internal System.Data.Linq.Table<ScoreObj> ScoreObjs
		{
			get
			{
				return this.GetTable<ScoreObj>();
			}
		}
		
		public System.Data.Linq.Table<SpecialObj> SpecialObjs
		{
			get
			{
				return this.GetTable<SpecialObj>();
			}
		}
		
		public System.Data.Linq.Table<Status> Status
		{
			get
			{
				return this.GetTable<Status>();
			}
		}
		
		internal System.Data.Linq.Table<FriendObj> FriendObjs
		{
			get
			{
				return this.GetTable<FriendObj>();
			}
		}
		
		internal System.Data.Linq.Table<VenuesObj> VenuesObjs
		{
			get
			{
				return this.GetTable<VenuesObj>();
			}
		}
		
		public System.Data.Linq.Table<VenueGroup> VenueGroups
		{
			get
			{
				return this.GetTable<VenueGroup>();
			}
		}
		
		internal System.Data.Linq.Table<VenueObj> VenueObjs
		{
			get
			{
				return this.GetTable<VenueObj>();
			}
		}
		
		internal System.Data.Linq.Table<CategoriesObj> CategoriesObjs
		{
			get
			{
				return this.GetTable<CategoriesObj>();
			}
		}
		
		internal System.Data.Linq.Table<UsersObj> UsersObjs
		{
			get
			{
				return this.GetTable<UsersObj>();
			}
		}
		
		internal System.Data.Linq.Table<RequestsObj> RequestsObjs
		{
			get
			{
				return this.GetTable<RequestsObj>();
			}
		}
		
		public System.Data.Linq.Table<Tip> Tips
		{
			get
			{
				return this.GetTable<Tip>();
			}
		}
		
		internal System.Data.Linq.Table<TipsObj> TipsObjs
		{
			get
			{
				return this.GetTable<TipsObj>();
			}
		}
		
		public System.Data.Linq.Table<TipGroup> TipGroups
		{
			get
			{
				return this.GetTable<TipGroup>();
			}
		}
		
		internal System.Data.Linq.Table<TipObj> TipObjs
		{
			get
			{
				return this.GetTable<TipObj>();
			}
		}
		
		public System.Data.Linq.Table<Stats> Stats
		{
			get
			{
				return this.GetTable<Stats>();
			}
		}
		
		public System.Data.Linq.Table<BeenHere> BeenHeres
		{
			get
			{
				return this.GetTable<BeenHere>();
			}
		}
		
		public System.Data.Linq.Table<ErrorObj> ErrorObjs
		{
			get
			{
				return this.GetTable<ErrorObj>();
			}
		}
		
		public System.Data.Linq.Table<SettingsObj> SettingsObjs
		{
			get
			{
				return this.GetTable<SettingsObj>();
			}
		}
		
		public System.Data.Linq.Table<HereNow> HereNows
		{
			get
			{
				return this.GetTable<HereNow>();
			}
		}
		
		public System.Data.Linq.Table<Groups> Groups
		{
			get
			{
				return this.GetTable<Groups>();
			}
		}
		
		public System.Data.Linq.Table<Items> Items
		{
			get
			{
				return this.GetTable<Items>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Checkin
	{
		
		private int _Id;
		
		private Schema.User _User;
		
		private Schema.Venue _Venue;
		
		private int _Distance;
		
		private string _Display;
		
		private string _Shout;
		
		private System.DateTimeOffset _Created;
		
		private string _Message;
		
		private Schema.Mayor _Mayor;
		
		private List<Schema.Badge> _Badges;
		
		private List<Schema.Score> _Scores;
		
		private List<Schema.SpecialObj> _Specials;
		
		private string _TimeZone;
		
		private bool _IsMayor;
		
		public Checkin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User", CanBeNull=false)]
		public Schema.User User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Venue", CanBeNull=false)]
		public Schema.Venue Venue
		{
			get
			{
				return this._Venue;
			}
			set
			{
				if ((this._Venue != value))
				{
					this._Venue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance")]
		public int Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this._Distance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Display", CanBeNull=false)]
		public string Display
		{
			get
			{
				return this._Display;
			}
			set
			{
				if ((this._Display != value))
				{
					this._Display = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shout", CanBeNull=false)]
		public string Shout
		{
			get
			{
				return this._Shout;
			}
			set
			{
				if ((this._Shout != value))
				{
					this._Shout = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created")]
		public System.DateTimeOffset Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this._Created = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mayor", CanBeNull=false)]
		public Schema.Mayor Mayor
		{
			get
			{
				return this._Mayor;
			}
			set
			{
				if ((this._Mayor != value))
				{
					this._Mayor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Badges", CanBeNull=true)]
		public List<Schema.Badge> Badges
		{
			get
			{
				return this._Badges;
			}
			set
			{
				if ((this._Badges != value))
				{
					this._Badges = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scores", CanBeNull=false)]
		public List<Schema.Score> Scores
		{
			get
			{
				return this._Scores;
			}
			set
			{
				if ((this._Scores != value))
				{
					this._Scores = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Specials", CanBeNull=false)]
		public List<Schema.SpecialObj> Specials
		{
			get
			{
				return this._Specials;
			}
			set
			{
				if ((this._Specials != value))
				{
					this._Specials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", CanBeNull=false)]
		public string TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this._TimeZone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMayor")]
		public bool IsMayor
		{
			get
			{
				return this._IsMayor;
			}
			set
			{
				if ((this._IsMayor != value))
				{
					this._IsMayor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class User
	{
		
		private int _Id;
		
		private string _FirstName;
		
		private string _LastName;
		
		private string _Photo;
		
		private string _Phone;
		
		private string _Email;
		
		private Schema.Gender _Gender;
		
		private string _Twitter;
		
		private long _Facebook;
		
		private Schema.FriendStatus _FriendStatus;
		
		private Schema.Checkin _Checkin;
		
		private Schema.Settings _Settings;
		
		private Schema.Status _Status;
		
		private List<Schema.Badge> _Badges;
		
		private List<Schema.Venue> _Mayor;
		
		public User()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", CanBeNull=false)]
		public string FirstName
		{
			get
			{
				return this._FirstName;
			}
			set
			{
				if ((this._FirstName != value))
				{
					this._FirstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", CanBeNull=false)]
		public string LastName
		{
			get
			{
				return this._LastName;
			}
			set
			{
				if ((this._LastName != value))
				{
					this._LastName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", CanBeNull=false)]
		public string Photo
		{
			get
			{
				return this._Photo;
			}
			set
			{
				if ((this._Photo != value))
				{
					this._Photo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", CanBeNull=false)]
		public Schema.Gender Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Twitter", CanBeNull=false)]
		public string Twitter
		{
			get
			{
				return this._Twitter;
			}
			set
			{
				if ((this._Twitter != value))
				{
					this._Twitter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facebook")]
		public long Facebook
		{
			get
			{
				return this._Facebook;
			}
			set
			{
				if ((this._Facebook != value))
				{
					this._Facebook = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FriendStatus", CanBeNull=false)]
		public Schema.FriendStatus FriendStatus
		{
			get
			{
				return this._FriendStatus;
			}
			set
			{
				if ((this._FriendStatus != value))
				{
					this._FriendStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checkin", CanBeNull=false)]
		public Schema.Checkin Checkin
		{
			get
			{
				return this._Checkin;
			}
			set
			{
				if ((this._Checkin != value))
				{
					this._Checkin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Settings", CanBeNull=false)]
		public Schema.Settings Settings
		{
			get
			{
				return this._Settings;
			}
			set
			{
				if ((this._Settings != value))
				{
					this._Settings = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", CanBeNull=false)]
		public Schema.Status Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Badges", CanBeNull=false)]
		public List<Schema.Badge> Badges
		{
			get
			{
				return this._Badges;
			}
			set
			{
				if ((this._Badges != value))
				{
					this._Badges = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mayor", CanBeNull=false)]
		public List<Schema.Venue> Mayor
		{
			get
			{
				return this._Mayor;
			}
			set
			{
				if ((this._Mayor != value))
				{
					this._Mayor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Venue
	{
		
		private int _Id;
		
		private string _Name;
		
		private string _Address;
		
		private string _CrossStreet;
		
		private string _Geolat;
		
		private string _Geolong;
		
		private string _City;
		
		private string _State;
		
		private string _Zip;
		
		private Schema.Category _PrimaryCategory;
		
		private string _Phone;
		
		private Schema.Stats _Stats;
		
		private List<Schema.Tip> _Tips;
		
		private List<Schema.Category> _Categories;
		
		private List<Schema.Special> _Specials;
		
		private Schema.HereNow _HereNow;
		
		public Venue()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrossStreet", CanBeNull=false)]
		public string CrossStreet
		{
			get
			{
				return this._CrossStreet;
			}
			set
			{
				if ((this._CrossStreet != value))
				{
					this._CrossStreet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geolat", CanBeNull=false)]
		public string Geolat
		{
			get
			{
				return this._Geolat;
			}
			set
			{
				if ((this._Geolat != value))
				{
					this._Geolat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Geolong", CanBeNull=false)]
		public string Geolong
		{
			get
			{
				return this._Geolong;
			}
			set
			{
				if ((this._Geolong != value))
				{
					this._Geolong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", CanBeNull=false)]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this._City = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", CanBeNull=false)]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this._State = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", CanBeNull=false)]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this._Zip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryCategory", CanBeNull=false)]
		public Schema.Category PrimaryCategory
		{
			get
			{
				return this._PrimaryCategory;
			}
			set
			{
				if ((this._PrimaryCategory != value))
				{
					this._PrimaryCategory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stats", CanBeNull=false)]
		public Schema.Stats Stats
		{
			get
			{
				return this._Stats;
			}
			set
			{
				if ((this._Stats != value))
				{
					this._Stats = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tips", CanBeNull=false)]
		public List<Schema.Tip> Tips
		{
			get
			{
				return this._Tips;
			}
			set
			{
				if ((this._Tips != value))
				{
					this._Tips = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categories", CanBeNull=false)]
		public List<Schema.Category> Categories
		{
			get
			{
				return this._Categories;
			}
			set
			{
				if ((this._Categories != value))
				{
					this._Categories = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Specials", CanBeNull=false)]
		public List<Schema.Special> Specials
		{
			get
			{
				return this._Specials;
			}
			set
			{
				if ((this._Specials != value))
				{
					this._Specials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HereNow", CanBeNull=false)]
		public Schema.HereNow HereNow
		{
			get
			{
				return this._HereNow;
			}
			set
			{
				if ((this._HereNow != value))
				{
					this._HereNow = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Mayor
	{
		
		private string _Type;
		
		private int _Count;
		
		private Schema.User _User;
		
		private string _Message;
		
		private int _Checkins;
		
		public Mayor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count")]
		public int Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this._Count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User", CanBeNull=false)]
		public Schema.User User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checkins")]
		public int Checkins
		{
			get
			{
				return this._Checkins;
			}
			set
			{
				if ((this._Checkins != value))
				{
					this._Checkins = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Badge
	{
		
		private int _Id;
		
		private string _Name;
		
		private string _Icon;
		
		private string _Description;
		
		public Badge()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", CanBeNull=false)]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this._Icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Score
	{
		
		private string _Points;
		
		private string _Icon;
		
		private string _Message;
		
		public Score()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Points", CanBeNull=false)]
		public string Points
		{
			get
			{
				return this._Points;
			}
			set
			{
				if ((this._Points != value))
				{
					this._Points = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Icon", CanBeNull=false)]
		public string Icon
		{
			get
			{
				return this._Icon;
			}
			set
			{
				if ((this._Icon != value))
				{
					this._Icon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Special
	{
		
		private int _Id;
		
		private Schema.SpecialType _Type;
		
		private Schema.SpecialKind _Kind;
		
		private string _Message;
		
		private Schema.Venue _Venue;
		
		public Special()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", CanBeNull=false)]
		public Schema.SpecialType Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kind", CanBeNull=false)]
		public Schema.SpecialKind Kind
		{
			get
			{
				return this._Kind;
			}
			set
			{
				if ((this._Kind != value))
				{
					this._Kind = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this._Message = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Venue", CanBeNull=false)]
		public Schema.Venue Venue
		{
			get
			{
				return this._Venue;
			}
			set
			{
				if ((this._Venue != value))
				{
					this._Venue = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Category
	{
		
		private int _Id;
		
		private string _FullPathName;
		
		private string _NodeName;
		
		private string _IconUrl;
		
		private List<Schema.Category> _Categories;
		
		public Category()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullPathName", CanBeNull=false)]
		public string FullPathName
		{
			get
			{
				return this._FullPathName;
			}
			set
			{
				if ((this._FullPathName != value))
				{
					this._FullPathName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeName", CanBeNull=false)]
		public string NodeName
		{
			get
			{
				return this._NodeName;
			}
			set
			{
				if ((this._NodeName != value))
				{
					this._NodeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IconUrl", CanBeNull=false)]
		public string IconUrl
		{
			get
			{
				return this._IconUrl;
			}
			set
			{
				if ((this._IconUrl != value))
				{
					this._IconUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categories", CanBeNull=false)]
		public List<Schema.Category> Categories
		{
			get
			{
				return this._Categories;
			}
			set
			{
				if ((this._Categories != value))
				{
					this._Categories = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Settings
	{
		
		private bool _SendToTwitter;
		
		private bool _SendToFacebook;
		
		private Schema.PingStatus _Pings;
		
		public Settings()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendToTwitter")]
		public bool SendToTwitter
		{
			get
			{
				return this._SendToTwitter;
			}
			set
			{
				if ((this._SendToTwitter != value))
				{
					this._SendToTwitter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendToFacebook")]
		public bool SendToFacebook
		{
			get
			{
				return this._SendToFacebook;
			}
			set
			{
				if ((this._SendToFacebook != value))
				{
					this._SendToFacebook = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pings", CanBeNull=false)]
		public Schema.PingStatus Pings
		{
			get
			{
				return this._Pings;
			}
			set
			{
				if ((this._Pings != value))
				{
					this._Pings = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class UserObj
	{
		
		private Schema.User _User;
		
		public UserObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User", CanBeNull=false)]
		public Schema.User User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class CheckinsObj
	{
		
		private List<Schema.Checkin> _Checkins;
		
		public CheckinsObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checkins", CanBeNull=false)]
		public List<Schema.Checkin> Checkins
		{
			get
			{
				return this._Checkins;
			}
			set
			{
				if ((this._Checkins != value))
				{
					this._Checkins = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class BadgeObj
	{
		
		private Schema.Badge _Badge;
		
		public BadgeObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Badge", CanBeNull=false)]
		public Schema.Badge Badge
		{
			get
			{
				return this._Badge;
			}
			set
			{
				if ((this._Badge != value))
				{
					this._Badge = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class CheckinObj
	{
		
		private Schema.Checkin _Checkin;
		
		public CheckinObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checkin", CanBeNull=false)]
		public Schema.Checkin Checkin
		{
			get
			{
				return this._Checkin;
			}
			set
			{
				if ((this._Checkin != value))
				{
					this._Checkin = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class ScoreObj
	{
		
		private Schema.Score _Score;
		
		public ScoreObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", CanBeNull=false)]
		public Schema.Score Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this._Score = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class SpecialObj
	{
		
		private Schema.Special _Special;
		
		public SpecialObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Special", CanBeNull=false)]
		public Schema.Special Special
		{
			get
			{
				return this._Special;
			}
			set
			{
				if ((this._Special != value))
				{
					this._Special = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Status
	{
		
		private string _FriendRequests;
		
		public Status()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FriendRequests", CanBeNull=false)]
		public string FriendRequests
		{
			get
			{
				return this._FriendRequests;
			}
			set
			{
				if ((this._FriendRequests != value))
				{
					this._FriendRequests = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class FriendObj
	{
		
		private List<Schema.User> _Friends;
		
		public FriendObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Friends", CanBeNull=false)]
		public List<Schema.User> Friends
		{
			get
			{
				return this._Friends;
			}
			set
			{
				if ((this._Friends != value))
				{
					this._Friends = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class VenuesObj
	{
		
		private List<Schema.VenueGroup> _Groups;
		
		public VenuesObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Groups", CanBeNull=false)]
		public List<Schema.VenueGroup> Groups
		{
			get
			{
				return this._Groups;
			}
			set
			{
				if ((this._Groups != value))
				{
					this._Groups = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class VenueGroup
	{
		
		private string _Type;
		
		private List<Schema.Venue> _Venues;
		
		public VenueGroup()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Venues", CanBeNull=false)]
		public List<Schema.Venue> Venues
		{
			get
			{
				return this._Venues;
			}
			set
			{
				if ((this._Venues != value))
				{
					this._Venues = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class VenueObj
	{
		
		private Schema.Venue _Venue;
		
		public VenueObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Venue", CanBeNull=false)]
		public Schema.Venue Venue
		{
			get
			{
				return this._Venue;
			}
			set
			{
				if ((this._Venue != value))
				{
					this._Venue = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class CategoriesObj
	{
		
		private List<Schema.Category> _Categories;
		
		public CategoriesObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categories", CanBeNull=false)]
		public List<Schema.Category> Categories
		{
			get
			{
				return this._Categories;
			}
			set
			{
				if ((this._Categories != value))
				{
					this._Categories = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class UsersObj
	{
		
		private List<Schema.User> _Users;
		
		public UsersObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Users", CanBeNull=false)]
		public List<Schema.User> Users
		{
			get
			{
				return this._Users;
			}
			set
			{
				if ((this._Users != value))
				{
					this._Users = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class RequestsObj
	{
		
		private List<Schema.User> _Requests;
		
		public RequestsObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Requests", CanBeNull=false)]
		public List<Schema.User> Requests
		{
			get
			{
				return this._Requests;
			}
			set
			{
				if ((this._Requests != value))
				{
					this._Requests = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Tip
	{
		
		private int _Id;
		
		private string _Text;
		
		private int _Distance;
		
		private System.DateTimeOffset _Created;
		
		private Schema.User _User;
		
		private Schema.Venue _Venue;
		
		private string _Status;
		
		public Tip()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Id")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distance")]
		public int Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				if ((this._Distance != value))
				{
					this._Distance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created")]
		public System.DateTimeOffset Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this._Created = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User", CanBeNull=false)]
		public Schema.User User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Venue", CanBeNull=false)]
		public Schema.Venue Venue
		{
			get
			{
				return this._Venue;
			}
			set
			{
				if ((this._Venue != value))
				{
					this._Venue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", CanBeNull=false)]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class TipsObj
	{
		
		private List<Schema.TipGroup> _Groups;
		
		public TipsObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Groups", CanBeNull=false)]
		public List<Schema.TipGroup> Groups
		{
			get
			{
				return this._Groups;
			}
			set
			{
				if ((this._Groups != value))
				{
					this._Groups = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class TipGroup
	{
		
		private string _Type;
		
		private List<Schema.Tip> _Tips;
		
		public TipGroup()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tips", CanBeNull=false)]
		public List<Schema.Tip> Tips
		{
			get
			{
				return this._Tips;
			}
			set
			{
				if ((this._Tips != value))
				{
					this._Tips = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	internal partial class TipObj
	{
		
		private Schema.Tip _Tip;
		
		public TipObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tip", CanBeNull=false)]
		public Schema.Tip Tip
		{
			get
			{
				return this._Tip;
			}
			set
			{
				if ((this._Tip != value))
				{
					this._Tip = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Stats
	{
		
		private int _Checkins;
		
		private int _HereNow;
		
		private Schema.BeenHere _BeenHere;
		
		private Schema.Mayor _Mayor;
		
		public Stats()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checkins")]
		public int Checkins
		{
			get
			{
				return this._Checkins;
			}
			set
			{
				if ((this._Checkins != value))
				{
					this._Checkins = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HereNow")]
		public int HereNow
		{
			get
			{
				return this._HereNow;
			}
			set
			{
				if ((this._HereNow != value))
				{
					this._HereNow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeenHere", CanBeNull=false)]
		public Schema.BeenHere BeenHere
		{
			get
			{
				return this._BeenHere;
			}
			set
			{
				if ((this._BeenHere != value))
				{
					this._BeenHere = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mayor", CanBeNull=false)]
		public Schema.Mayor Mayor
		{
			get
			{
				return this._Mayor;
			}
			set
			{
				if ((this._Mayor != value))
				{
					this._Mayor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class BeenHere
	{
		
		private bool _Me;
		
		public BeenHere()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Me")]
		public bool Me
		{
			get
			{
				return this._Me;
			}
			set
			{
				if ((this._Me != value))
				{
					this._Me = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class ErrorObj
	{
		
		private string _Error;
		
		private string _Unauthorized;
		
		private string _RateLimited;
		
		public ErrorObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", CanBeNull=false)]
		public string Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this._Error = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unauthorized", CanBeNull=false)]
		public string Unauthorized
		{
			get
			{
				return this._Unauthorized;
			}
			set
			{
				if ((this._Unauthorized != value))
				{
					this._Unauthorized = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RateLimited", CanBeNull=false)]
		public string RateLimited
		{
			get
			{
				return this._RateLimited;
			}
			set
			{
				if ((this._RateLimited != value))
				{
					this._RateLimited = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class SettingsObj
	{
		
		private Schema.Settings _Settings;
		
		public SettingsObj()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Settings", CanBeNull=false)]
		public Schema.Settings Settings
		{
			get
			{
				return this._Settings;
			}
			set
			{
				if ((this._Settings != value))
				{
					this._Settings = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class HereNow
	{
		
		private int _Count;
		
		private Schema.Groups _Groups;
		
		public HereNow()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count")]
		public int Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this._Count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Groups", CanBeNull=false)]
		public Schema.Groups Groups
		{
			get
			{
				return this._Groups;
			}
			set
			{
				if ((this._Groups != value))
				{
					this._Groups = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Groups
	{
		
		private string _Type;
		
		private string _Name;
		
		private int _Count;
		
		private string _Items;
		
		public Groups()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count")]
		public int Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this._Count = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Items", CanBeNull=false)]
		public string Items
		{
			get
			{
				return this._Items;
			}
			set
			{
				if ((this._Items != value))
				{
					this._Items = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Items
	{
		
		private long _ID;
		
		private string _CreatedAt;
		
		private string _Type;
		
		private string _TimeZone;
		
		private Schema.User _User;
		
		public Items()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedAt", CanBeNull=false)]
		public string CreatedAt
		{
			get
			{
				return this._CreatedAt;
			}
			set
			{
				if ((this._CreatedAt != value))
				{
					this._CreatedAt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeZone", CanBeNull=false)]
		public string TimeZone
		{
			get
			{
				return this._TimeZone;
			}
			set
			{
				if ((this._TimeZone != value))
				{
					this._TimeZone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User", CanBeNull=false)]
		public Schema.User User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this._User = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
